# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://keepsimpler.github.io/xinai/"

git_url = "https://github.com/keepsimpler/xinai/tree/master/"

def custom_doc_links(name): return None
